In [1]:
import psycopg2

def pgconnect():
    
    try: 
        conn = psycopg2.connect(host='localhost', database='assignment', user='postgres', password='6688')

        print('connected')
    except Exception as e:
        print("unable to connect to the database")
        print(e)
    return conn

In [2]:
conn = pgconnect()

connected

In [3]:
import csv
data_CensusStats = list(csv.DictReader(open('CensusStats.csv')))
data_CensusStats

[OrderedDict([('area_id', '102011028'),
              ('median_annual_household_income', '46996'),
              ('avg_monthly_rent', '1906')]),
 OrderedDict([('area_id', '102011029'),
              ('median_annual_household_income', '42621'),
              ('avg_monthly_rent', '1682')]),
 OrderedDict([('area_id', '102011030'),
              ('median_annual_household_income', '42105'),
              ('avg_monthly_rent', '1182')]),
 OrderedDict([('area_id', '102011031'),
              ('median_annual_household_income', '43481'),
              ('avg_monthly_rent', '1595')]),
 OrderedDict([('area_id', '102011032'),
              ('median_annual_household_income', '45972'),
              ('avg_monthly_rent', '1382')]),
 OrderedDict([('area_id', '102011033'),
              ('median_annual_household_income', '47896'),
              ('avg_monthly_rent', '1649')]),
 OrderedDict([('area_id', '102011034'),
              ('median_annual_household_income', '41642'),
              ('avg_monthly_rent', '1397')]),
 OrderedDict([('area_id', '102011035'),
              ('median_annual_household_income', '46660'),
              ('avg_monthly_rent', '1512')]),
 OrderedDict([('area_id', '102011036'),
              ('median_annual_household_income', '45762'),
              ('avg_monthly_rent', '1495')]),
 OrderedDict([('area_id', '102011037'),
              ('median_annual_household_income', '45966'),
              ('avg_monthly_rent', '1572')]),
 OrderedDict([('area_id', '102011038'),
              ('median_annual_household_income', '43171'),
              ('avg_monthly_rent', '1667')]),
 OrderedDict([('area_id', '102011039'),
              ('median_annual_household_income', '46422'),
              ('avg_monthly_rent', '2022')]),
 OrderedDict([('area_id', '102011040'),
              ('median_annual_household_income', '40252'),
              ('avg_monthly_rent', '1517')]),
 OrderedDict([('area_id', '102011041'),
              ('median_annual_household_income', '47295'),
              ('avg_monthly_rent', '1902')]),
 OrderedDict([('area_id', '102011042'),
              ('median_annual_household_income', '42481'),
              ('avg_monthly_rent', '1387')]),
 OrderedDict([('area_id', '102011043'),
              ('median_annual_household_income', '43438'),
              ('avg_monthly_rent', '1466')]),
 OrderedDict([('area_id', '102021044'),
              ('median_annual_household_income', '42469'),
              ('avg_monthly_rent', '1423')]),
 OrderedDict([('area_id', '102021045'),
              ('median_annual_household_income', '42641'),
              ('avg_monthly_rent', '1526')]),
 OrderedDict([('area_id', '102021046'),
              ('median_annual_household_income', '41702'),
              ('avg_monthly_rent', '1347')]),
 OrderedDict([('area_id', '102021047'),
              ('median_annual_household_income', '45015'),
              ('avg_monthly_rent', '1593')]),
 OrderedDict([('area_id', '102021048'),
              ('median_annual_household_income', '41051'),
              ('avg_monthly_rent', '1330')]),
 OrderedDict([('area_id', '102021049'),
              ('median_annual_household_income', '44122'),
              ('avg_monthly_rent', '1364')]),
 OrderedDict([('area_id', '102021050'),
              ('median_annual_household_income', '41152'),
              ('avg_monthly_rent', '1363')]),
 OrderedDict([('area_id', '102021051'),
              ('median_annual_household_income', '48214'),
              ('avg_monthly_rent', '1469')]),
 OrderedDict([('area_id', '102021052'),
              ('median_annual_household_income', '42683'),
              ('avg_monthly_rent', '1455')]),
 OrderedDict([('area_id', '102021053'),
              ('median_annual_household_income', '44137'),
              ('avg_monthly_rent', '1404')]),
 OrderedDict([('area_id', '102021054'),
              ('median_annual_household_income', '39615'),
              ('avg_monthly_rent', '1296')]),
 OrderedDict([('area_id', '102021055'),
              ('median_annual_household_income', '44360'),
              ('avg_monthly_rent', '1699')]),
 OrderedDict([('area_id', '102021056'),
              ('median_annual_household_income', '47983'),
              ('avg_monthly_rent', '1823')]),
 OrderedDict([('area_id', '102021057'),
              ('median_annual_household_income', '41055'),
              ('avg_monthly_rent', '1276')]),
 OrderedDict([('area_id', '115011290'),
              ('median_annual_household_income', '52019'),
              ('avg_monthly_rent', '2166')]),
 OrderedDict([('area_id', '115011291'),
              ('median_annual_household_income', '53703'),
              ('avg_monthly_rent', '2521')]),
 OrderedDict([('area_id', '115011294'),
              ('median_annual_household_income', '50112'),
              ('avg_monthly_rent', '2661')]),
 OrderedDict([('area_id', '115011296'),
              ('median_annual_household_income', '53907'),
              ('avg_monthly_rent', '2605')]),
 OrderedDict([('area_id', '115011553'),
              ('median_annual_household_income', '50992'),
              ('avg_monthly_rent', '2360')]),
 OrderedDict([('area_id', '115011554'),
              ('median_annual_household_income', '48100'),
              ('avg_monthly_rent', '2088')]),
 OrderedDict([('area_id', '115011555'),
              ('median_annual_household_income', '52307'),
              ('avg_monthly_rent', '2519')]),
 OrderedDict([('area_id', '115011556'),
              ('median_annual_household_income', '52563'),
              ('avg_monthly_rent', '2387')]),
 OrderedDict([('area_id', '115011557'),
              ('median_annual_household_income', '58568'),
              ('avg_monthly_rent', '2828')]),
 OrderedDict([('area_id', '115011558'),
              ('median_annual_household_income', '50744'),
              ('avg_monthly_rent', '2756')]),
 OrderedDict([('area_id', '115011559'),
              ('median_annual_household_income', '55461'),
              ('avg_monthly_rent', '2681')]),
 OrderedDict([('area_id', '115021297'),
              ('median_annual_household_income', '48550'),
              ('avg_monthly_rent', '1972')]),
 OrderedDict([('area_id', '115021298'),
              ('median_annual_household_income', '45128'),
              ('avg_monthly_rent', '1897')]),
 OrderedDict([('area_id', '115031299'),
              ('median_annual_household_income', '40176'),
              ('avg_monthly_rent', '906')]),
 OrderedDict([('area_id', '115031300'),
              ('median_annual_household_income', '49194'),
              ('avg_monthly_rent', '1619')]),
 OrderedDict([('area_id', '115041301'),
              ('median_annual_household_income', '50076'),
              ('avg_monthly_rent', '1793')]),
 OrderedDict([('area_id', '115041302'),
              ('median_annual_household_income', '56607'),
              ('avg_monthly_rent', '2605')]),
 OrderedDict([('area_id', '116011303'),
              ('median_annual_household_income', '45814'),
              ('avg_monthly_rent', '1587')]),
 OrderedDict([('area_id', '116011304'),
              ('median_annual_household_income', '45946'),
              ('avg_monthly_rent', '1493')]),
 OrderedDict([('area_id', '116011306'),
              ('median_annual_household_income', '49909'),
              ('avg_monthly_rent', '1371')]),
 OrderedDict([('area_id', '116011307'),
              ('median_annual_household_income', '49783'),
              ('avg_monthly_rent', '1435')]),
 OrderedDict([('area_id', '116011308'),
              ('median_annual_household_income', '48147'),
              ('avg_monthly_rent', '1587')]),
 OrderedDict([('area_id', '116011560'),
              ('median_annual_household_income', '45529'),
              ('avg_monthly_rent', '1567')]),
 OrderedDict([('area_id', '116011561'),
              ('median_annual_household_income', '46244'),
              ('avg_monthly_rent', '1680')]),
 OrderedDict([('area_id', '116021309'),
              ('median_annual_household_income', '54647'),
              ('avg_monthly_rent', '2411')]),
 OrderedDict([('area_id', '116021310'),
              ('median_annual_household_income', '60354'),
              ('avg_monthly_rent', '2462')]),
 OrderedDict([('area_id', '116021312'),
              ('median_annual_household_income', '49900'),
              ('avg_monthly_rent', '1891')]),
 OrderedDict([('area_id', '116021562'),
              ('median_annual_household_income', '57409'),
              ('avg_monthly_rent', '2245')]),
 OrderedDict([('area_id', '116021563'),
              ('median_annual_household_income', '53386'),
              ('avg_monthly_rent', '1895')]),
 OrderedDict([('area_id', '116031313'),
              ('median_annual_household_income', '42863'),
              ('avg_monthly_rent', '1123')]),
 OrderedDict([('area_id', '116031314'),
              ('median_annual_household_income', '50279'),
              ('avg_monthly_rent', '1713')]),
 OrderedDict([('area_id', '116031315'),
              ('median_annual_household_income', '49534'),
              ('avg_monthly_rent', '1750')]),
 OrderedDict([('area_id', '116031316'),
              ('median_annual_household_income', '46525'),
              ('avg_monthly_rent', '1253')]),
 OrderedDict([('area_id', '116031317'),
              ('median_annual_household_income', '42774'),
              ('avg_monthly_rent', '1383')]),
 OrderedDict([('area_id', '116031318'),
              ('median_annual_household_income', '53113'),
              ('avg_monthly_rent', '')]),
 OrderedDict([('area_id', '116031319'),
              ('median_annual_household_income', '49012'),
              ('avg_monthly_rent', '1688')]),
 OrderedDict([('area_id', '117011320'),
              ('median_annual_household_income', '49680'),
              ('avg_monthly_rent', '')]),
 OrderedDict([('area_id', '117011321'),
              ('median_annual_household_income', '56444'),
              ('avg_monthly_rent', '2133')]),
 OrderedDict([('area_id', '117011322'),
              ('median_annual_household_income', '47831'),
              ('avg_monthly_rent', '2160')]),
 OrderedDict([('area_id', '117011323'),
              ('median_annual_household_income', '47465'),
              ('avg_monthly_rent', '1705')]),
 OrderedDict([('area_id', '117011324'),
              ('median_annual_household_income', ''),
              ('avg_monthly_rent', '')]),
 OrderedDict([('area_id', '117011325'),
              ('median_annual_household_income', ''),
              ('avg_monthly_rent', '')]),
 OrderedDict([('area_id', '117021326'),
              ('median_annual_household_income', '51843'),
              ('avg_monthly_rent', '2001')]),
 OrderedDict([('area_id', '117021327'),
              ('median_annual_household_income', '58029'),
              ('avg_monthly_rent', '2173')]),
 OrderedDict([('area_id', '117021328'),
              ('median_annual_household_income', '55708'),
              ('avg_monthly_rent', '2452')]),
 OrderedDict([('area_id', '117031329'),
              ('median_annual_household_income', '59293'),
              ('avg_monthly_rent', '2491')]),
 OrderedDict([('area_id', '117031330'),
              ('median_annual_household_income', '69680'),
              ('avg_monthly_rent', '2581')]),
 OrderedDict([('area_id', '117031331'),
              ('median_annual_household_income', '56691'),
              ('avg_monthly_rent', '2162')]),
 OrderedDict([('area_id', '117031332'),
              ('median_annual_household_income', '58210'),
              ('avg_monthly_rent', '2270')]),
 OrderedDict([('area_id', '117031333'),
              ('median_annual_household_income', '58253'),
              ('avg_monthly_rent', '2256')]),
 OrderedDict([('area_id', '117031334'),
              ('median_annual_household_income', '47393'),
              ('avg_monthly_rent', '2575')]),
 OrderedDict([('area_id', '117031335'),
              ('median_annual_household_income', '51347'),
              ('avg_monthly_rent', '2193')]),
 OrderedDict([('area_id', '117031336'),
              ('median_annual_household_income', '58396'),
              ('avg_monthly_rent', '2342')]),
 OrderedDict([('area_id', '117031337'),
              ('median_annual_household_income', '27311'),
              ('avg_monthly_rent', '2998')]),
 OrderedDict([('area_id', '117031338'),
              ('median_annual_household_income', '57055'),
              ('avg_monthly_rent', '2302')]),
 OrderedDict([('area_id', '118011339'),
              ('median_annual_household_income', '60000'),
              ('avg_monthly_rent', '2699')]),
 OrderedDict([('area_id', '118011340'),
              ('median_annual_household_income', '59384'),
              ('avg_monthly_rent', '2783')]),
 OrderedDict([('area_id', '118011341'),
              ('median_annual_household_income', '56457'),
              ('avg_monthly_rent', '2630')]),
 OrderedDict([('area_id', '118011342'),
              ('median_annual_household_income', ''),
              ('avg_monthly_rent', '')]),
 OrderedDict([('area_id', '118011343'),
              ('median_annual_household_income', '72578'),
              ('avg_monthly_rent', '2883')]),
 OrderedDict([('area_id', '118011344'),
              ('median_annual_household_income', '61041'),
              ('avg_monthly_rent', '2677')]),
 OrderedDict([('area_id', '118011345'),
              ('median_annual_household_income', '71227'),
              ('avg_monthly_rent', '2627')]),
 OrderedDict([('area_id', '118011346'),
              ('median_annual_household_income', '68973'),
              ('avg_monthly_rent', '2890')]),
 OrderedDict([('area_id', '118011347'),
              ('median_annual_household_income', '70707'),
              ('avg_monthly_rent', '2879')]),
 OrderedDict([('area_id', '118021348'),
              ('median_annual_household_income', '65825'),
              ('avg_monthly_rent', '2453')]),
 OrderedDict([('area_id', '118021350'),
              ('median_annual_household_income', '52678'),
              ('avg_monthly_rent', '1846')]),
 OrderedDict([('area_id', '118021564'),
              ('median_annual_household_income', '50113'),
              ('avg_monthly_rent', '2315')]),
 OrderedDict([('area_id', '118021565'),
              ('median_annual_household_income', '45863'),
              ('avg_monthly_rent', '2312')]),
 OrderedDict([('area_id', '118021566'),
              ('median_annual_household_income', '57188'),
              ('avg_monthly_rent', '2564')]),
 OrderedDict([('area_id', '118021567'),
              ('median_annual_household_income', '52086'),
              ('avg_monthly_rent', '1817')]),
 OrderedDict([('area_id', '118021568'),
              ('median_annual_household_income', '50049'),
              ('avg_monthly_rent', '2547')]),
 OrderedDict([('area_id', '118021569'),
              ('median_annual_household_income', '63216'),
              ('avg_monthly_rent', '2465')]),
 OrderedDict([('area_id', '118021570'),
              ('median_annual_household_income', '58849'),
              ('avg_monthly_rent', '2459')]),
 OrderedDict([('area_id', '119011354'),
              ('median_annual_household_income', '42000'),
              ('avg_monthly_rent', '1386')]),
 OrderedDict([('area_id', '119011355'),
              ('median_annual_household_income', '41625'),
              ('avg_monthly_rent', '2280')]),
 OrderedDict([('area_id', '119011356'),
              ('median_annual_household_income', '40953'),
              ('avg_monthly_rent', '1877')]),
 OrderedDict([('area_id', '119011357'),
              ('median_annual_household_income', '38037'),
              ('avg_monthly_rent', '1525')]),
 OrderedDict([('area_id', '119011358'),
              ('median_annual_household_income', '47300'),
              ('avg_monthly_rent', '1668')]),
 OrderedDict([('area_id', '119011359'),
              ('median_annual_household_income', '50481'),
              ('avg_monthly_rent', '1712')]),
 OrderedDict([('area_id', '119011360'),
              ('median_annual_household_income', '47488'),
              ('avg_monthly_rent', '1679')]),
 OrderedDict([('area_id', '119011361'),
              ('median_annual_household_income', '40040'),
              ('avg_monthly_rent', '1545')]),
 OrderedDict([('area_id', '119011571'),
              ('median_annual_household_income', '38068'),
              ('avg_monthly_rent', '1621')]),
 OrderedDict([('area_id', '119011572'),
              ('median_annual_household_income', '38469'),
              ('avg_monthly_rent', '1573')]),
 OrderedDict([('area_id', '119021362'),
              ('median_annual_household_income', '41731'),
              ('avg_monthly_rent', '1609')]),
 OrderedDict([('area_id', '119021363'),
              ('median_annual_household_income', '37977'),
              ('avg_monthly_rent', '1750')]),
 OrderedDict([('area_id', '119021364'),
              ('median_annual_household_income', '48560'),
              ('avg_monthly_rent', '2074')]),
 OrderedDict([('area_id', '119021366'),
              ('median_annual_household_income', '36909'),
              ('avg_monthly_rent', '1581')]),
 OrderedDict([('area_id', '119021367'),
              ('median_annual_household_income', '42765'),
              ('avg_monthly_rent', '1750')]),
 OrderedDict([('area_id', '119021573'),
              ('median_annual_household_income', '33672'),
              ('avg_monthly_rent', '1563')]),
 OrderedDict([('area_id', '119021574'),
              ('median_annual_household_income', '35072'),
              ('avg_monthly_rent', '1554')]),
 OrderedDict([('area_id', '119031368'),
              ('median_annual_household_income', '38371'),
              ('avg_monthly_rent', '2023')]),
 OrderedDict([('area_id', '119031369'),
              ('median_annual_household_income', '48513'),
              ('avg_monthly_rent', '1827')]),
 OrderedDict([('area_id', '119031370'),
              ('median_annual_household_income', '41759'),
              ('avg_monthly_rent', '1620')]),
 OrderedDict([('area_id', '119031371'),
              ('median_annual_household_income', '50641'),
              ('avg_monthly_rent', '2081')]),
 OrderedDict([('area_id', '119031372'),
              ('median_annual_household_income', '47417'),
              ('avg_monthly_rent', '1743')]),
 OrderedDict([('area_id', '119031373'),
              ('median_annual_household_income', '40157'),
              ('avg_monthly_rent', '1259')]),
 OrderedDict([('area_id', '119031374'),
              ('median_annual_household_income', '44799'),
              ('avg_monthly_rent', '2046')]),
 OrderedDict([('area_id', '119041375'),
              ('median_annual_household_income', '45664'),
              ('avg_monthly_rent', '2255')]),
 OrderedDict([('area_id', '119041376'),
              ('median_annual_household_income', '44388'),
              ('avg_monthly_rent', '1937')]),
 OrderedDict([('area_id', '119041377'),
              ('median_annual_household_income', '45274'),
              ('avg_monthly_rent', '1915')]),
 OrderedDict([('area_id', '119041378'),
              ('median_annual_household_income', '47168'),
              ('avg_monthly_rent', '1996')]),
 OrderedDict([('area_id', '119041379'),
              ('median_annual_household_income', '46083'),
              ('avg_monthly_rent', '1968')]),
 OrderedDict([('area_id', '119041380'),
              ('median_annual_household_income', '49203'),
              ('avg_monthly_rent', '1960')]),
 OrderedDict([('area_id', '119041381'),
              ('median_annual_household_income', '42272'),
              ('avg_monthly_rent', '2024')]),
 OrderedDict([('area_id', '119041382'),
              ('median_annual_household_income', '50608'),
              ('avg_monthly_rent', '2009')]),
 OrderedDict([('area_id', '120011383'),
              ('median_annual_household_income', '54465'),
              ('avg_monthly_rent', '2439')]),
 OrderedDict([('area_id', '120011384'),
              ('median_annual_household_income', '49761'),
              ('avg_monthly_rent', '2473')]),
 OrderedDict([('area_id', '120011385'),
              ('median_annual_household_income', '64309'),
              ('avg_monthly_rent', '2467')]),

In [4]:
def pgexec( conn, sqlcmd, args, msg, silent=False ):
   """ utility function to execute some SQL statement
       can take optional arguments to fill in (dictionary)
       error and transaction handling built-in """
   retval = False
   with conn:
      with conn.cursor() as cur:
         try:
            if args is None:
               cur.execute(sqlcmd)
            else:
               cur.execute(sqlcmd, args)
            if silent == False: 
                print("success: " + msg)
            retval = True
         except Exception as e:
            if silent == False: 
                print("db error: ")
                print(e)
   return retval

# 1st: login to database

conn = pgconnect()

# if you want to reset the table
pgexec (conn, "DROP TABLE IF EXISTS CensusStats", None, "Reset Table CensusStats")

# 2nd: ensure that the schema is in place

CensusStats_schema = """CREATE TABLE IF NOT EXISTS CensusStats (
                                 area_id BIGINT PRIMARY KEY,
                                 median_annual_household_income INT,
                                 avg_monthly_rent INT                                 
                           )"""
pgexec (conn, CensusStats_schema, None, "Create Table CensusStats")

# 3nd: load data
# IMPORTANT: make sure the header line of CSV is without spaces!
insert_stmt = """INSERT INTO CensusStats(area_id, median_annual_household_income, avg_monthly_rent) VALUES (%(area_id)s, %(median_annual_household_income)s, %(avg_monthly_rent)s)"""
for row in data_CensusStats:
    pgexec (conn, insert_stmt, row, "row inserted")

connected
success: Reset Table CensusStats
success: Create Table CensusStats
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
db error:
错误:  无效的整数类型输入语法: ""
LINE 1: ..._income, avg_monthly_rent) VALUES ('116031318', '53113', '')
                                                                    ^

success: row inserted
db error:
错误:  无效的整数类型输入语法: ""
LINE 1: ..._income, avg_monthly_rent) VALUES ('117011320', '49680', '')
                                                                    ^

success: row inserted
success: row inserted
success: row inserted
db error:
错误:  无效的整数类型输入语法: ""
LINE 1: ...ehold_income, avg_monthly_rent) VALUES ('117011324', '', '')
                                                                ^

db error:
错误:  无效的整数类型输入语法: ""
LINE 1: ...ehold_income, avg_monthly_rent) VALUES ('117011325', '', '')
                                                                ^

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
db error:
错误:  无效的整数类型输入语法: ""
LINE 1: ...ehold_income, avg_monthly_rent) VALUES ('118011342', '', '')
                                                                ^

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
db error:
错误:  无效的整数类型输入语法: ""
LINE 1: ...ehold_income, avg_monthly_rent) VALUES ('123021439', '', '')
                                                                ^

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
db error:
错误:  无效的整数类型输入语法: ""
LINE 1: ...ehold_income, avg_monthly_rent) VALUES ('124011451', '', '')
                                                                ^

success: row inserted
success: row inserted
success: row inserted
success: row inserted
db error:
错误:  无效的整数类型输入语法: ""
LINE 1: ...ehold_income, avg_monthly_rent) VALUES ('124021456', '', '')
                                                                ^

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
db error:
错误:  无效的整数类型输入语法: ""
LINE 1: ...ehold_income, avg_monthly_rent) VALUES ('125011475', '', '')
                                                                ^

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
db error:
错误:  无效的整数类型输入语法: ""
LINE 1: ..._income, avg_monthly_rent) VALUES ('125031486', '57326', '')
                                                                    ^

db error:
错误:  无效的整数类型输入语法: ""
LINE 1: ..._income, avg_monthly_rent) VALUES ('125031487', '35000', '')
                                                                    ^

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
db error:
错误:  无效的整数类型输入语法: ""
LINE 1: ..._income, avg_monthly_rent) VALUES ('127021521', '46348', '')
                                                                    ^

success: row inserted
success: row inserted
success: row inserted

success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
success: row inserted
db error:
错误:  无效的整数类型输入语法: ""
LINE 1: ...ld_income, avg_monthly_rent) VALUES ('128021537', '', '1899'...
                                                             ^

success: row inserted
success: row inserted
success: row inserted
success: row inserted

In [5]:
def pgquery( conn, sqlcmd, args, silent=False ):
   """ utility function to execute some SQL query statement
       can take optional arguments to fill in (dictionary)
       will print out on screen the result set of the query
       error and transaction handling built-in """
   retval = False
   with conn:
      with conn.cursor() as cur:
         try:
            if args is None:
                cur.execute(sqlcmd)
            else:
                cur.execute(sqlcmd, args)
            if silent == False:
                for record in cur:
                    print(record)
            retval = True
         except Exception as e:
            if silent == False:
                print("db read error: ")
                print(e)
   return retval

In [6]:
# PRINT THE CONTENT OF TABLE
query_stmt = "SELECT * FROM CensusStats"
print(query_stmt)
pgquery (conn, query_stmt, None)

SELECT * FROM CensusStats
(102011028, 46996, 1906)
(102011029, 42621, 1682)
(102011030, 42105, 1182)
(102011031, 43481, 1595)
(102011032, 45972, 1382)
(102011033, 47896, 1649)
(102011034, 41642, 1397)
(102011035, 46660, 1512)
(102011036, 45762, 1495)
(102011037, 45966, 1572)
(102011038, 43171, 1667)
(102011039, 46422, 2022)
(102011040, 40252, 1517)
(102011041, 47295, 1902)
(102011042, 42481, 1387)
(102011043, 43438, 1466)
(102021044, 42469, 1423)
(102021045, 42641, 1526)
(102021046, 41702, 1347)
(102021047, 45015, 1593)
(102021048, 41051, 1330)
(102021049, 44122, 1364)
(102021050, 41152, 1363)
(102021051, 48214, 1469)
(102021052, 42683, 1455)
(102021053, 44137, 1404)
(102021054, 39615, 1296)
(102021055, 44360, 1699)
(102021056, 47983, 1823)
(102021057, 41055, 1276)
(115011290, 52019, 2166)
(115011291, 53703, 2521)
(115011294, 50112, 2661)
(115011296, 53907, 2605)
(115011553, 50992, 2360)
(115011554, 48100, 2088)
(115011555, 52307, 2519)
(115011556, 52563, 2387)
(115011557, 58568, 2828)
(115011558, 50744, 2756)
(115011559, 55461, 2681)
(115021297, 48550, 1972)
(115021298, 45128, 1897)
(115031299, 40176, 906)
(115031300, 49194, 1619)
(115041301, 50076, 1793)
(115041302, 56607, 2605)
(116011303, 45814, 1587)
(116011304, 45946, 1493)
(116011306, 49909, 1371)
(116011307, 49783, 1435)
(116011308, 48147, 1587)
(116011560, 45529, 1567)
(116011561, 46244, 1680)
(116021309, 54647, 2411)
(116021310, 60354, 2462)
(116021312, 49900, 1891)
(116021562, 57409, 2245)
(116021563, 53386, 1895)
(116031313, 42863, 1123)
(116031314, 50279, 1713)
(116031315, 49534, 1750)
(116031316, 46525, 1253)
(116031317, 42774, 1383)
(116031319, 49012, 1688)
(117011321, 56444, 2133)
(117011322, 47831, 2160)
(117011323, 47465, 1705)
(117021326, 51843, 2001)
(117021327, 58029, 2173)
(117021328, 55708, 2452)
(117031329, 59293, 2491)
(117031330, 69680, 2581)
(117031331, 56691, 2162)
(117031332, 58210, 2270)
(117031333, 58253, 2256)
(117031334, 47393, 2575)
(117031335, 51347, 2193)
(117031336, 58396, 2342)
(117031337, 27311, 2998)
(117031338, 57055, 2302)
(118011339, 60000, 2699)
(118011340, 59384, 2783)
(118011341, 56457, 2630)
(118011343, 72578, 2883)
(118011344, 61041, 2677)
(118011345, 71227, 2627)
(118011346, 68973, 2890)
(118011347, 70707, 2879)
(118021348, 65825, 2453)
(118021350, 52678, 1846)
(118021564, 50113, 2315)
(118021565, 45863, 2312)
(118021566, 57188, 2564)
(118021567, 52086, 1817)
(118021568, 50049, 2547)
(118021569, 63216, 2465)
(118021570, 58849, 2459)
(119011354, 42000, 1386)
(119011355, 41625, 2280)
(119011356, 40953, 1877)
(119011357, 38037, 1525)
(119011358, 47300, 1668)
(119011359, 50481, 1712)
(119011360, 47488, 1679)
(119011361, 40040, 1545)
(119011571, 38068, 1621)
(119011572, 38469, 1573)
(119021362, 41731, 1609)
(119021363, 37977, 1750)
(119021364, 48560, 2074)
(119021366, 36909, 1581)
(119021367, 42765, 1750)
(119021573, 33672, 1563)
(119021574, 35072, 1554)
(119031368, 38371, 2023)
(119031369, 48513, 1827)
(119031370, 41759, 1620)
(119031371, 50641, 2081)
(119031372, 47417, 1743)
(119031373, 40157, 1259)
(119031374, 44799, 2046)
(119041375, 45664, 2255)
(119041376, 44388, 1937)
(119041377, 45274, 1915)
(119041378, 47168, 1996)
(119041379, 46083, 1968)
(119041380, 49203, 1960)
(119041381, 42272, 2024)
(119041382, 50608, 2009)
(120011383, 54465, 2439)
(120011384, 49761, 2473)
(120011385, 64309, 2467)
(120011386, 60675, 2299)
(120021387, 75494, 2478)
(120021388, 65700, 2359)
(120021389, 72101, 2570)
(120031390, 44851, 1936)
(120031391, 40592, 2163)
(120031392, 51520, 1991)
(120031393, 47788, 1855)
(120031394, 56326, 2020)
(120031395, 55995, 2040)
(120031396, 44552, 1988)
(120031575, 43081, 2185)
(120031576, 50332, 2035)
(121011398, 51040, 2542)
(121011399, 56793, 2333)
(121011400, 66402, 2455)
(121011401, 73803, 2626)
(121011402, 64660, 2780)
(121021403, 52106, 2263)
(121021404, 50973, 2231)
(121021406, 53829, 2040)
(121021577, 48707, 1958)
(121021578, 49963, 1843)
(121021579, 52084, 2136)
(121031407, 54843, 2810)
(121031408, 60723, 2724)
(121031409, 60263, 2849)
(121031410, 54318, 3045)
(121031411, 54672, 2643)
(121031412, 59998, 2736)
(121041413, 71016, 2610)
(121041414, 69923, 2522)
(121041415, 71177, 2629)
(121041416, 69417, 2416)
(121041417, 71668, 2749)
(122011418, 63192, 2777)
(122011419, 61658, 2823)
(122021420, 47971, 2774)
(122021421, 49645, 2560)
(122021422, 51543, 2635)
(122021423, 50548, 2668)
(122031424, 46442, 2081)
(122031425, 48709, 2600)
(122031426, 51076, 2257)
(122031427, 51711, 2584)
(122031428, 50761, 3121)
(122031429, 58561, 2462)
(122031430, 53046, 2237)
(122031431, 52322, 2376)
(122031432, 53481, 2573)
(123011433, 52309, 1608)
(123011434, 54903, 1907)
(123011435, 55784, 1927)
(123021436, 46534, 1318)
(123021437, 47794, 1538)
(123021438, 48683, 1373)
(123021440, 48035, 1546)
(123021441, 47961, 1439)
(123021442, 46145, 1384)
(123021443, 46667, 1394)
(123021444, 47557, 1414)
(123031445, 47811, 1625)
(123031446, 53629, 1673)
(123031447, 49070, 1507)
(123031448, 48925, 1449)
(124011449, 39202, 1352)
(124011450, 52702, 1741)
(124011452, 37965, 1349)
(124011453, 46669, 1433)
(124011454, 49953, 1596)
(124011455, 42963, 1547)
(124031457, 49719, 1578)
(124031458, 53043, 1771)
(124031459, 53366, 1664)
(124031460, 56033, 1885)
(124031461, 50659, 1574)
(124031462, 48669, 1404)
(124031463, 55083, 1921)
(124031464, 47708, 1376)
(124031465, 50100, 1526)
(124041466, 46052, 1518)
(124041467, 49265, 1495)
(124041468, 46692, 1660)
(124051469, 51802, 1828)
(124051470, 51261, 1755)
(124051580, 46724, 1526)
(124051581, 45361, 1401)
(125011473, 56312, 2302)
(125011582, 30683, 1860)
(125011583, 30931, 1638)
(125011584, 35500, 1665)
(125011585, 36622, 1608)
(125011586, 37656, 1991)
(125011587, 39931, 1506)
(125021476, 44262, 2157)
(125021477, 47634, 1560)
(125021478, 45233, 1539)
(125031479, 40574, 1437)
(125031480, 38240, 1238)
(125031481, 38842, 1617)
(125031482, 50280, 1880)
(125031483, 37265, 1416)
(125031484, 42581, 1587)
(125031485, 43083, 1662)
(125041489, 50053, 1770)
(125041490, 49540, 2322)
(125041491, 53421, 1854)
(125041492, 45022, 1812)
(125041493, 48768, 1697)
(125041494, 53011, 2092)
(125041588, 47891, 1605)
(125041589, 47543, 1652)
(126011495, 48326, 2301)
(126011496, 54941, 2248)
(126021497, 43900, 2018)
(126021498, 58409, 1955)
(126021499, 69385, 2175)
(126021500, 49507, 2029)
(126021501, 50953, 2105)
(126021503, 50035, 1913)
(126021590, 55111, 2760)
(126021591, 49745, 2055)
(127011504, 39804, 1078)
(127011505, 43499, 1658)
(127011506, 52101, 2130)
(127011592, 46021, 553)
(127011593, 49992, 2185)
(127011594, 44997, 1709)
(127011595, 47263, 1969)
(127011596, 50130, 2010)
(127011597, 52146, 2129)
(127021509, 43245, 1447)
(127021510, 46473, 1791)
(127021511, 36969, 1354)
(127021512, 41018, 1376)
(127021513, 39741, 1405)
(127021514, 44267, 1681)
(127021515, 39685, 1478)
(127021516, 39701, 1679)
(127021517, 45071, 1640)
(127021518, 48258, 1684)
(127021519, 43457, 1535)
(127021520, 43397, 1727)
(127031522, 47580, 1703)
(127031523, 50891, 1913)
(127031524, 57000, 1805)
(127031598, 42303, 1495)
(127031599, 40864, 1217)
(127031600, 51121, 2044)
(127031601, 43106, 1275)
(128011529, 52871, 2113)
(128011530, 50319, 1879)
(128011531, 47383, 2059)
(128011602, 52754, 1814)
(128011603, 52088, 2606)
(128011604, 55083, 2027)
(128011605, 57429, 3086)
(128011606, 56652, 2200)
(128021533, 49791, 1785)
(128021534, 51600, 2608)
(128021535, 54420, 2183)
(128021536, 55391, 1947)
(128021538, 53378, 1809)
(128021607, 52667, 1955)
(128021608, 51243, 2163)
(128021609, 54935, 2300)

True